plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
baseurl: /oaio

title: Judging Machine
description: A machine that writes texts.
